[workspace]
members = [
  "zomes/test",
  "zomes/test-integrity"
]
resolver = "2"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"


[workspace.dependencies]
hdi = "=0.5.0-dev.10"
hdk = "=0.4.0-dev.12"
serde = "1"
