[package]
name = "test_integrity"
version = "0.1.1"
authors = [ "zo-el <joelulahanna@gmail.com>", "jetttech <lisa.jetton@holo.host>" ]
edition = "2021"

[lib]
name = "test_integrity"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdi = { workspace = true }
serde = { workspace = true }
