name: Main CI and CD

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Fetch source code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27

      - name: Set up cachix
        uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - name: Build Nix packages
        run: nix develop -c $SHELL -c "echo Nix packages built"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore zome build
        uses: actions/cache/restore@v3
        with:
          path: |
            .cargo
            target
          key: ${{ runner.os }}-build-happ-${{ hashFiles('Cargo.lock') }}

      - name: 🔎 Build happ
        run: make nix-build

      - name: version
        run: |
          make version
          VERSION=$(make version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        id: version
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          body_path: version-manager.json
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload test.happ artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test.happ
          asset_name: test.happ
          asset_content_type: application/happ
      - name: upload test.dna artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test.dna
          asset_name: test.dna
          asset_content_type: application/dna
      - name: upload test-skip-proof.happ artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./test-skip-proof.happ
          asset_name: test-skip-proof.happ
          asset_content_type: application/happ
